kind: Secret
apiVersion: v1
metadata:
  name: example-secret1
  annotations:
    avp.kubernetes.io/path: "gitlab/data/creds"
type: Opaque
stringData:
  username: <path:gitlab/creds#username>
  password: <path:gitlab/creds#password>
